[package]
name = "splashscreen"
version = "0.1.0"
description = "An example Tauri Application with a splashscreen"
edition = "2021"
rust-version = "1.57"
license = "Apache-2.0 OR MIT"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build" }

[dependencies]
tauri = { path = "../../../core/tauri", features = [] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
ui = []
