# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Udeps

on:
  pull_request:
    paths:
      - '.github/workflows/udeps.yml'
      - 'core/**'
      - 'tooling/bundler/**'
      - 'tooling/cli/**'

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0 # This is set to 0 by the https://github.com/Swatinem/rust-cache
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.

jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Cache cargo state
        uses: actions/cache@v2
        env:
          cache-name: cargo-state
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          restore-keys: |
            ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-
            ubuntu-latest-nightly-${{ env.cache-name }}-
            ubuntu-latest-nightly-
            ubuntu-latest-

      - name: Cache core cargo target
        uses: actions/cache@v2
        env:
          cache-name: cargo-core
        with:
          path: target
          # Add date to the cache to keep it up to date
          key: ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('core/**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('core/**/Cargo.toml') }}
            ubuntu-latest-nightly-${{ env.cache-name }}-
            ubuntu-latest-nightly-
            ubuntu-latest-

      - name: Cache bundler cargo target
        uses: actions/cache@v2
        env:
          cache-name: cargo-bundler
        with:
          path: tooling/bundler/target
          # Add date to the cache to keep it up to date
          key: ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('tooling/bundler/Cargo.lock') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('tooling/bundler/Cargo.lock') }}
            ubuntu-latest-nightly-${{ env.cache-name }}-
            ubuntu-latest-nightly-
            ubuntu-latest-

      - name: Cache CLI cargo target
        uses: actions/cache@v2
        env:
          cache-name: cargo-cli
        with:
          path: tooling/cli/target
          # Add date to the cache to keep it up to date
          key: ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('tooling/cli/Cargo.lock') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ubuntu-latest-nightly-${{ env.cache-name }}-${{ hashFiles('tooling/cli/Cargo.lock') }}
            ubuntu-latest-nightly-${{ env.cache-name }}-
            ubuntu-latest-nightly-
            ubuntu-latest-

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked --force

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --all-targets --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --manifest-path ./tooling/bundler/Cargo.toml --all-targets --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --manifest-path ./tooling/cli/Cargo.toml --all-targets --all-features
